### ISSUE TITLE
Bootstrap 5.2 compatibility

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight#2781]
- [x] https://github.com/projectblacklight/blacklight/pull/2780
- [x] https://github.com/projectblacklight/blacklight/pull/2782
![Screen Shot 2022-07-20 at 17 06 20](https://user-images.githubusercontent.com/111218/180102872-f37d1c71-e63d-4873-a60b-398de8728274.png)

- [x] pagination should not have rounded corners (upstream bug: https://github.com/twbs/bootstrap/issues/36820)
![Screen Shot 2022-07-20 at 17 08 01](https://user-images.githubusercontent.com/111218/180103022-cc8b4133-77c9-4055-95b0-4a3ab653eff1.png)

- [ ] ~https://github.com/projectblacklight/blacklight/pull/2784~
![Screen Shot 2022-07-20 at 17 18 15](https://user-images.githubusercontent.com/111218/180103851-936c5bba-3449-452c-a9ba-1c9fff7dfa5a.png)

- [x] show tools lost their button-y ness
![Uploading Screen Shot 2022-07-20 at 17.18.55.png…]()

- [x] search history labels should be more centered
![Screen Shot 2022-07-20 at 17 19 59](https://user-images.githubusercontent.com/111218/180103989-9538ecec-54d9-4fa5-b614-5b0e21cdf432.png)

- [x] advanced search fields lost their margin
![Screen Shot 2022-07-20 at 17 26 49](https://user-images.githubusercontent.com/111218/180104579-61d34a20-ddb0-4005-b47b-8e8e6166a140.png)

- [x] advanced search sort widget lost its interactive appearance:
![Screen Shot 2022-07-20 at 17 27 38](https://user-images.githubusercontent.com/111218/180104645-0584034f-b737-405d-8485-66bac4c8e48a.png)

- [x] home page jumbotron button background disappeared (bootstrap 5 regression)
![Screen Shot 2022-07-20 at 17 21 11](https://user-images.githubusercontent.com/111218/180104111-a60ed502-b686-485b-a807-d75cb6f7d4d4.png)

- [x] modal styling is gone (bootstrap 5.1 didn't look so good either; is this a regression from #2671?)
![Screen Shot 2022-07-20 at 17 22 17](https://user-images.githubusercontent.com/111218/180104197-504b1c79-2f6e-417a-ab65-e43c7e0b2c5a.png)

- [x] #2831 facet link underlining is a bit much (bootstrap 5 regression)
